import type { NextRequest } from 'next/server'
import { NextResponse } from 'next/server'
import { generateTechnicalReportPDF } from '@/lib/pdf-generator'

// Dados de teste para cada cenário
const testScenarios = {
  excelente: {
    id: 'test-excelente',
    reportNumber: 'LDO-2026-99999',
    reportType: 'PREMIUM',
    deviceModel: 'iPhone 15 Pro Max',
    deviceType: 'IPHONE',
    storage: '256GB',
    color: 'Titânio Natural',
    imei: '356789012345678',
    serialNumber: 'F2LY3456ABC',
    screenCondition: 'PERFEITO',
    screenConditionNotes: 'Sem arranhões ou marcas visíveis',
    bodyCondition: 'PERFEITO',
    bodyConditionNotes: 'Estado impecável',
    cameraCondition: 'PERFEITO',
    cameraConditionNotes: 'Lentes sem arranhões',
    batteryHealthPercent: 98,
    batteryHealthPhoto: null,
    touchWorking: true,
    faceIdWorking: true,
    wifiWorking: true,
    bluetoothWorking: true,
    speakersWorking: true,
    microphoneWorking: true,
    vibrationWorking: true,
    buttonsWorking: true,
    camerasWorking: true,
    icloudFree: true,
    carrierUnlocked: true,
    hasWaterDamage: false,
    hasRepairs: false,
    repairDetails: null,
    hasBox: true,
    hasCharger: true,
    hasCable: true,
    hasEarphones: true,
    hasInvoice: true,
    hasPencil: false,
    hasKeyboard: false,
    frontPhoto: null,
    backPhoto: null,
    sidesPhotos: null,
    screenOnPhoto: null,
    screenOffPhoto: null,
    imeiPhoto: null,
    boxPhoto: null,
    invoicePhoto: null,
    accessoriesPhotos: null,
    createdAt: new Date(),
    expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    evaluationId: 'eval-test',
    userId: 'user-test',
  },
  bom: {
    id: 'test-bom',
    reportNumber: 'LDO-2026-88888',
    reportType: 'STANDARD',
    deviceModel: 'iPhone 14 Pro',
    deviceType: 'IPHONE',
    storage: '128GB',
    color: 'Roxo Profundo',
    imei: '356789012345679',
    serialNumber: 'F2LY3456ABD',
    screenCondition: 'LEVES_MARCAS',
    screenConditionNotes: 'Alguns micro arranhões',
    bodyCondition: 'LEVES_MARCAS',
    bodyConditionNotes: 'Marcas de uso nas bordas',
    cameraCondition: 'PERFEITO',
    cameraConditionNotes: '-',
    batteryHealthPercent: 85,
    batteryHealthPhoto: null,
    touchWorking: true,
    faceIdWorking: true,
    wifiWorking: true,
    bluetoothWorking: true,
    speakersWorking: true,
    microphoneWorking: true,
    vibrationWorking: true,
    buttonsWorking: true,
    camerasWorking: true,
    icloudFree: true,
    carrierUnlocked: true,
    hasWaterDamage: false,
    hasRepairs: false,
    repairDetails: null,
    hasBox: true,
    hasCharger: false,
    hasCable: true,
    hasEarphones: false,
    hasInvoice: false,
    hasPencil: false,
    hasKeyboard: false,
    frontPhoto: null,
    backPhoto: null,
    sidesPhotos: null,
    screenOnPhoto: null,
    screenOffPhoto: null,
    imeiPhoto: null,
    boxPhoto: null,
    invoicePhoto: null,
    accessoriesPhotos: null,
    createdAt: new Date(),
    expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    evaluationId: 'eval-test',
    userId: 'user-test',
  },
  regular: {
    id: 'test-regular',
    reportNumber: 'LDO-2026-77777',
    reportType: 'STANDARD',
    deviceModel: 'iPhone 13',
    deviceType: 'IPHONE',
    storage: '128GB',
    color: 'Azul',
    imei: '356789012345680',
    serialNumber: 'F2LY3456ABE',
    screenCondition: 'VISIVEIS_MARCAS',
    screenConditionNotes: 'Arranhões visíveis na tela',
    bodyCondition: 'VISIVEIS_MARCAS',
    bodyConditionNotes: 'Amassados leves nas bordas',
    cameraCondition: 'LEVES_MARCAS',
    cameraConditionNotes: 'Arranhão leve na lente',
    batteryHealthPercent: 72,
    batteryHealthPhoto: null,
    touchWorking: true,
    faceIdWorking: true,
    wifiWorking: false,
    bluetoothWorking: true,
    speakersWorking: true,
    microphoneWorking: true,
    vibrationWorking: true,
    buttonsWorking: true,
    camerasWorking: true,
    icloudFree: true,
    carrierUnlocked: true,
    hasWaterDamage: false,
    hasRepairs: false,
    repairDetails: null,
    hasBox: false,
    hasCharger: true,
    hasCable: true,
    hasEarphones: false,
    hasInvoice: false,
    hasPencil: false,
    hasKeyboard: false,
    frontPhoto: null,
    backPhoto: null,
    sidesPhotos: null,
    screenOnPhoto: null,
    screenOffPhoto: null,
    imeiPhoto: null,
    boxPhoto: null,
    invoicePhoto: null,
    accessoriesPhotos: null,
    createdAt: new Date(),
    expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    evaluationId: 'eval-test',
    userId: 'user-test',
  },
  ruim: {
    id: 'test-ruim',
    reportNumber: 'LDO-2026-66666',
    reportType: 'BASIC',
    deviceModel: 'iPhone 12',
    deviceType: 'IPHONE',
    storage: '64GB',
    color: 'Preto',
    imei: '356789012345681',
    serialNumber: 'F2LY3456ABF',
    screenCondition: 'TRINCADO',
    screenConditionNotes: 'Trinca no canto superior direito',
    bodyCondition: 'DANIFICADO',
    bodyConditionNotes: 'Amassados e arranhões profundos',
    cameraCondition: 'DANIFICADO',
    cameraConditionNotes: 'Lente trincada',
    batteryHealthPercent: 65,
    batteryHealthPhoto: null,
    touchWorking: false,
    faceIdWorking: true,
    wifiWorking: false,
    bluetoothWorking: true,
    speakersWorking: false,
    microphoneWorking: true,
    vibrationWorking: true,
    buttonsWorking: true,
    camerasWorking: false,
    icloudFree: true,
    carrierUnlocked: false,
    hasWaterDamage: true,
    hasRepairs: true,
    repairDetails: 'Tela substituída anteriormente',
    hasBox: false,
    hasCharger: false,
    hasCable: false,
    hasEarphones: false,
    hasInvoice: false,
    hasPencil: false,
    hasKeyboard: false,
    frontPhoto: null,
    backPhoto: null,
    sidesPhotos: null,
    screenOnPhoto: null,
    screenOffPhoto: null,
    imeiPhoto: null,
    boxPhoto: null,
    invoicePhoto: null,
    accessoriesPhotos: null,
    createdAt: new Date(),
    expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    evaluationId: 'eval-test',
    userId: 'user-test',
  },
  ipad: {
    id: 'test-ipad',
    reportNumber: 'LDO-2026-55555',
    reportType: 'PREMIUM',
    deviceModel: 'iPad Pro 11" M4 (2024)',
    deviceType: 'IPAD',
    storage: '512GB',
    color: 'Space Gray',
    imei: '356789012345682',
    serialNumber: 'DMPY3456ABC',
    screenCondition: 'PERFEITO',
    screenConditionNotes: 'Tela impecável',
    bodyCondition: 'LEVES_MARCAS',
    bodyConditionNotes: 'Micro arranhões na parte traseira',
    cameraCondition: 'PERFEITO',
    cameraConditionNotes: '-',
    batteryHealthPercent: 94,
    batteryHealthPhoto: null,
    touchWorking: true,
    faceIdWorking: true,
    wifiWorking: true,
    bluetoothWorking: true,
    speakersWorking: true,
    microphoneWorking: true,
    vibrationWorking: true,
    buttonsWorking: true,
    camerasWorking: true,
    icloudFree: true,
    carrierUnlocked: true,
    hasWaterDamage: false,
    hasRepairs: false,
    repairDetails: null,
    hasBox: true,
    hasCharger: true,
    hasCable: true,
    hasEarphones: false,
    hasInvoice: true,
    hasPencil: true,
    hasKeyboard: true,
    frontPhoto: null,
    backPhoto: null,
    sidesPhotos: null,
    screenOnPhoto: null,
    screenOffPhoto: null,
    imeiPhoto: null,
    boxPhoto: null,
    invoicePhoto: null,
    accessoriesPhotos: null,
    createdAt: new Date(),
    expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    evaluationId: 'eval-test',
    userId: 'user-test',
  },
}

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const scenario = searchParams.get('scenario') || 'excelente'

  if (!testScenarios[scenario as keyof typeof testScenarios]) {
    return NextResponse.json(
      { error: 'Cenário inválido. Use: excelente, bom, regular, ruim ou ipad' },
      { status: 400 }
    )
  }

  try {
    const report = testScenarios[scenario as keyof typeof testScenarios]
    const pdfBlob = await generateTechnicalReportPDF(report as any)
    
    const buffer = Buffer.from(await pdfBlob.arrayBuffer())
    
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Laudo_Teste_${scenario}_${report.reportNumber}.pdf"`,
      },
    })
  } catch (error) {
    console.error('Erro ao gerar PDF:', error)
    return NextResponse.json(
      { error: 'Erro ao gerar PDF' },
      { status: 500 }
    )
  }
}
